# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 02:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watershedpipe',
            name='connectionID',
            field=models.CharField(default=datetime.datetime(2017, 5, 2, 2, 27, 19, 151122, tzinfo=utc), max_length=20, primary_key=True, serialize=False, verbose_name='cID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watershedpipe',
            name='watershedID',
            field=models.CharField(max_length=20, verbose_name='wID'),
        ),
        migrations.AlterUniqueTogether(
            name='watershedpipe',
            unique_together=set([]),
        ),
        migrations.AlterModelTable(
            name='watershedpipe',
            table=None,
        ),
    ]
