# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watershed',
            options={'managed': False},
        ),
    ]
