# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatershedPipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watershedID', models.CharField(max_length=20, verbose_name='wID')),
                ('pipeID', models.CharField(max_length=20, verbose_name='pID')),
            ],
            options={
                'db_table': 'WatershedPipe',
            },
        ),
        migrations.AlterModelOptions(
            name='ffinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='florafauna',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='manmadefeature',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='naturalfeature',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='watershed',
            options={'managed': False},
        ),
        migrations.AlterUniqueTogether(
            name='watershedpipe',
            unique_together=set([('watershedID', 'pipeID')]),
        ),
    ]
