# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0002_auto_20170414_1752'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='watershed',
            table='Watershed',
        ),
    ]
