# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0002_auto_20170501_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watershedpipe',
            name='id',
        ),
        migrations.AlterField(
            model_name='watershedpipe',
            name='watershedID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='wID'),
        ),
        migrations.AlterModelTable(
            name='ffinfo',
            table='ffInfo',
        ),
        migrations.AlterModelTable(
            name='florafauna',
            table='FloraFauna',
        ),
        migrations.AlterModelTable(
            name='maintenance',
            table='Maintenance',
        ),
        migrations.AlterModelTable(
            name='manmadefeature',
            table='ManmadeFeature',
        ),
        migrations.AlterModelTable(
            name='naturalfeature',
            table='NaturalFeature',
        ),
        migrations.AlterModelTable(
            name='observation',
            table='Observation',
        ),
        migrations.AlterModelTable(
            name='watershed',
            table='Watershed',
        ),
    ]
