# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0002_auto_20170501_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watershedpipe',
            options={'managed': False},
        ),
    ]
