# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0003_auto_20170415_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='florafauna',
            options={'managed': False},
        ),
    ]
