# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0004_auto_20170419_0904'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='florafauna',
            table='FloraFauna',
        ),
    ]
