# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0005_auto_20170419_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'managed': False},
        ),
    ]
