# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0006_auto_20170419_2049'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maintenance',
            table='Maintenance',
        ),
    ]
