# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0008_auto_20170421_1435'),
        ('watershed', '0008_auto_20170420_1436'),
    ]

    operations = [
    ]
