# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watershed', '0009_merge'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ffinfo',
            table='ffInfo',
        ),
        migrations.AlterModelTable(
            name='manmadefeature',
            table='ManmadeFeature',
        ),
        migrations.AlterModelTable(
            name='naturalfeature',
            table='NaturalFeature',
        ),
        migrations.AlterModelTable(
            name='observation',
            table='Observation',
        ),
    ]
